// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function addArticle(data: {
	title: string;
	content: string;
	url?: string;
	sourceType: string;
}): Promise<{
	url: string | null;
	id: string;
	userId: string;
	title: string;
	content: string;
	sourceType: string;
	summary: string | null;
	keyPoints: string | null;
	topics: string | null;
	aiStatus: string;
	aiJobId: number | null;
	createdAt: Date;
	updatedAt: Date;
}>;
export declare function getArticles(filter?: {
	tag?: string;
	topic?: string;
	search?: string;
}): Promise<any[]>;
export declare function getArticle(id: string): Promise<any>;
export declare function deleteArticle(id: string): Promise<{
	success: boolean;
}>;
export declare function getArticleJobStatus(articleId: string): Promise<{
	aiStatus: string;
}>;
export declare function getAllTags(): Promise<{
	name: string;
	count: number;
}[]>;
export declare function getConcepts(): Promise<{
	articleIds: string[];
	id: string;
	userId: string;
	createdAt: Date;
	updatedAt: Date;
	name: string;
	description: string;
}[]>;
export declare function askQuestion(question: string): Promise<{
	queryId: string;
}>;
export declare function getQueryStatus(queryId: string): Promise<{
	queryId: string;
	isComplete: boolean;
	question: string;
	answer: string | null;
	sources: string[];
	createdAt: Date;
}>;
export declare function getSavedQueries(): Promise<{
	sources: string[];
	isComplete: boolean;
	id: string;
	userId: string;
	createdAt: Date;
	question: string;
	answer: string;
}[]>;
export declare function deleteQuery(id: string): Promise<{
	success: boolean;
}>;
export declare function getLibraryStats(): Promise<{
	totalArticles: number;
	processedArticles: number;
	totalTags: number;
	totalConcepts: number;
	totalQueries: number;
}>;

export {};
