// Generated by dts-bundle-generator v9.5.1

/**
 * Universal AI adapter — wraps Vercel AI SDK to support all providers.
 *
 * On Adaptive (hosted): falls back to mcp.promptAgent() if no AISettings configured.
 * Locally: reads provider + API key from AISettings in the DB (set via the Settings page).
 *
 * Usage:
 *   const result = await generateJSON<MyType>(prompt, jsonSchema, userId);
 *   const text   = await generateText(prompt, userId);
 */
export type AIProvider = "anthropic" | "openai" | "google" | "mistral" | "groq" | "openrouter" | "ollama";
export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function addArticle(data: {
	title: string;
	content: string;
	url?: string;
	sourceType: string;
}): Promise<{
	url: string | null;
	id: string;
	userId: string;
	updatedAt: Date;
	title: string;
	content: string;
	sourceType: string;
	contentHash: string | null;
	summary: string | null;
	keyPoints: string | null;
	topics: string | null;
	aiStatus: string;
	aiJobId: number | null;
	createdAt: Date;
} | {
	duplicate: boolean;
	url: string | null;
	id: string;
	userId: string;
	updatedAt: Date;
	title: string;
	content: string;
	sourceType: string;
	contentHash: string | null;
	summary: string | null;
	keyPoints: string | null;
	topics: string | null;
	aiStatus: string;
	aiJobId: number | null;
	createdAt: Date;
} | {
	duplicate: boolean;
	id: string;
	title: string;
}>;
export declare function getArticles(filter?: {
	tag?: string;
	topic?: string;
	search?: string;
}): Promise<any[]>;
export declare function getArticle(id: string): Promise<any>;
export declare function deleteArticle(id: string): Promise<{
	success: boolean;
}>;
export declare function getArticleJobStatus(articleId: string): Promise<{
	aiStatus: string;
}>;
export declare function getAllTags(): Promise<{
	name: string;
	count: number;
}[]>;
export declare function getConcepts(): Promise<{
	articleIds: string[];
	id: string;
	userId: string;
	updatedAt: Date;
	name: string;
	description: string;
	createdAt: Date;
}[]>;
export declare function askQuestion(question: string): Promise<{
	queryId: string;
}>;
export declare function getQueryStatus(queryId: string): Promise<{
	queryId: string;
	isComplete: boolean;
	question: string;
	answer: string | null;
	sources: string[];
	createdAt: Date;
}>;
export declare function getSavedQueries(): Promise<{
	sources: string[];
	isComplete: boolean;
	id: string;
	userId: string;
	createdAt: Date;
	question: string;
	answer: string;
}[]>;
export declare function deleteQuery(id: string): Promise<{
	success: boolean;
}>;
export declare function getGraphData(): Promise<{
	nodes: {
		id: string;
		title: string;
		aiStatus: string;
		topics: string[];
		sourceType: string;
		createdAt: Date;
	}[];
	edges: {
		id: string;
		source: string;
		target: string;
		strength: number;
		reason: string;
	}[];
	concepts: {
		id: string;
		name: string;
		articleIds: string[];
	}[];
}>;
export declare function exportObsidianVault(): Promise<{
	files: Record<string, string>;
}>;
export declare function ingestInboxFile(data: {
	filename: string;
	content: string;
}): Promise<{
	articleId: string;
	title: string;
	duplicate: boolean;
} | {
	articleId: string;
	title: string;
	duplicate?: undefined;
}>;
export declare function getAISettings(): Promise<{
	provider: AIProvider;
	model: string;
	apiKeySet: boolean;
	apiKeyPreview: string;
	ollamaUrl: string;
}>;
export declare function saveAISettings(data: {
	provider: string;
	model: string;
	apiKey?: string;
	ollamaUrl?: string;
}): Promise<{
	success: boolean;
}>;
export declare function testAIConnection(data: {
	provider: string;
	model: string;
	apiKey: string;
	ollamaUrl?: string;
}): Promise<{
	ok: boolean;
	error?: string;
}>;
export declare function adminCleanupDuplicates(): Promise<{
	deleted: number;
	message: string;
}>;
export declare function getLibraryStats(): Promise<{
	totalArticles: number;
	processedArticles: number;
	totalTags: number;
	totalConcepts: number;
	totalQueries: number;
}>;

export {};
